import type { GuideRoleContent } from '../../types';

export const GUIDE_CONTENT: GuideRoleContent[] = [
  {
    role: 'landlord',
    label: '房東',
    icon: 'real_estate_agent',
    intro: '從設定收款資訊、建立房源，到租客入住、每月抄表出帳與續約退租，依下列順序操作即可完成一整個租賃週期。',
    flow: [
      { label: '基本設定', sectionId: 'landlord-settings' },
      { label: '建立房源', sectionId: 'landlord-rooms' },
      { label: '租客入住', sectionId: 'landlord-onboarding' },
      { label: '簽約', sectionId: 'landlord-contract' },
      { label: '點交', sectionId: 'landlord-inspection' },
      { label: '每月抄表', sectionId: 'landlord-meter' },
      { label: '出帳收款', sectionId: 'landlord-billing' },
      { label: '續約／退租', sectionId: 'landlord-tenants' },
    ],
    sections: [
      {
        id: 'landlord-settings',
        title: '第一次使用：系統設定',
        icon: 'settings',
        location: '側邊欄底部 › 系統設定',
        summary: '收款帳戶、帳單日期與簽名會帶進帳單、收據與合約，建議開始出帳前先設定好。',
        steps: [
          '在「基本資料」填寫顯示名稱、聯絡電話與身分證號（合約出租人欄位會使用）。',
          '在「預設收款帳戶」填寫銀行代碼、帳號與戶名，租客查看帳單時會看到這組匯款資訊。',
          '在「每月帳單週期」設定每月幾號發送帳單、幾號前繳費。',
          '在「我的簽名／印章」簽名並設定 PIN 碼，之後簽合約、開收據時輸入 PIN 即可套用。',
        ],
        tips: [
          '綁定自己的 LINE 後，租客上傳繳費截圖等事件會即時通知您。',
          '忘記簽名 PIN 無法還原，只能重新簽名。',
        ],
        illustration: 'landlord-settings',
        routeName: 'Settings',
      },
      {
        id: 'landlord-rooms',
        title: '建立與瀏覽房源',
        icon: 'bedroom_parent',
        location: '側邊欄 › 房源管理',
        summary: '每間房一筆資料，包含照片、租金與電表群組；可用卡片或列表檢視，並依租約狀態篩選。',
        steps: [
          '按右上角「新增房源」，上傳 1～10 張照片（點照片可設為封面），填寫房號、租金、坪數與格局後儲存。',
          '用上方按鈕切換「卡片／列表」檢視，系統會記住您的選擇。',
          '列表檢視中點任一列，會展開該房間的照片縮圖；點縮圖可放大，左右切換瀏覽。',
          '用「租約狀態」篩選 60 天內到期、已過期或資料待確認的房間。',
        ],
        tips: [
          '「建物」分頁可登錄地址、稅籍、火險並把房間指派到建物，年度損益與稅費會依建物歸屬計算。',
          '出租中的房間到期日以目前生效的合約為準，要修改租期請到「租客列表」。',
        ],
        illustration: 'landlord-rooms',
        routeName: 'RoomManagement',
      },
      {
        id: 'landlord-onboarding',
        title: '新租客入住（上線精靈）',
        icon: 'person_add',
        location: '儀表板 › 新租客上線「開始」',
        summary: '以四個步驟帶您完成新租客入住，除了建檔，其他步驟都可以先跳過、之後再補。',
        steps: [
          '在儀表板按「開始」進入精靈；也可以先按「邀請填資料」，把線上填表連結傳給租客自行填寫。',
          '建檔：填寫租客資料並選擇房源，系統會一併建立租客登入帳號。',
          '簽約：房源與租客資料會自動帶入合約，雙方當場簽名。',
          '收押金、入住點交：開立押金收據，並與租客逐項點交房內物品。',
        ],
        tips: [
          '中途離開沒關係，到「租客列表」點該租客，按「繼續上線」即可接續。',
          '租客線上填表送出後，會出現在租客列表上方「待確認的線上填表」，按「核可建檔」即可。',
        ],
        illustration: 'landlord-onboarding',
        routeName: 'OnboardingMode',
      },
      {
        id: 'landlord-contract',
        title: '電子合約與紙本合約',
        icon: 'history_edu',
        location: '側邊欄 › 工具 › 電子合約',
        summary: '線上簽署或上傳紙本掃描檔，所有合約集中在「合約記錄」，並自動標示目前哪一份生效。',
        steps: [
          '在「新建合約」選擇房源與租客，資料會自動帶入，確認租期與費用約定。',
          '房東與租客分別完成簽名，勾選確認後按「確認簽署並產生合約」。',
          '若同一位租客已有租期重疊的合約，系統會先提示，確認後舊合約會標示為「已被取代」。',
          '在「合約記錄」查看每份合約的狀態：待生效、生效中、已被取代、已到期。',
        ],
        tips: [
          '合約若顯示「尚未連結租客帳號」，選擇租客後按「連結」，租客端才看得到並能線上確認。',
          '續約產生的新合約，起租日前會顯示「待生效」，不會跟目前的合約衝突。',
        ],
        illustration: 'landlord-contract',
        routeName: 'Contract',
      },
      {
        id: 'landlord-inspection',
        title: '入住與退租點交',
        icon: 'handshake',
        location: '租客列表 › 點選租客 › 入住點交／退租點交',
        summary: '雙方在同一台裝置上逐項確認物品與屋況並拍照存證，簽名後產生 PDF，退租時可以對照入住時的狀況。',
        steps: [
          '房東選擇要點交的物品與屋況項目（可沿用上次同房間的清單）。',
          '把裝置交給租客，租客逐項確認狀況並拍照。',
          '租客完成後把裝置交還，房東輸入簽名 PIN 取回操作。',
          '房東二次確認，有歧異的項目雙方協調後，由雙方簽名完成。',
        ],
        tips: [
          '退租點交會帶出入住時的狀況與照片，之後「辦理退租」會依惡化程度預填賠償比例。',
          '點交物品主檔可在「系統設定 › 點交物品主檔」先建好。',
        ],
        illustration: 'landlord-inspection',
        routeName: 'TenantList',
      },
      {
        id: 'landlord-meter',
        title: '每月抄電表',
        icon: 'electric_meter',
        location: '側邊欄 › 電表登錄',
        summary: '輸入各房本期電表度數，系統依您設定的計費方式算出電費，公共電費也會自動分攤。',
        steps: [
          '確認上方「抄表月份」是否正確。',
          '如果採用總表分攤制，先輸入台電總表的本期度數與帳單金額。',
          '在每一列填入房間的「本期讀數」，按 Tab 或 Enter 會跳到下一格。',
          '確認用量與電費後按「儲存紀錄」，再按「前往帳務管理，生成帳單」。',
        ],
        tips: [
          '費率、級距、雙月累計與電表群組在「計算參數設定」調整。',
          '列表出現琥珀色「個別方案」表示該房設定與全域設定不同，可以帶入全域設定。',
        ],
        illustration: 'landlord-meter',
        routeName: 'MeterReading',
      },
      {
        id: 'landlord-billing',
        title: '出帳與收款',
        icon: 'payments',
        location: '側邊欄 › 帳務管理 › 收款',
        summary: '一鍵產生當月租金與電費帳單，依租客收款；支援部分付款、前期欠款與預收沖抵。',
        steps: [
          '選擇月份後按「一鍵生成帳單」，在出帳預覽確認金額、前期欠款與預收沖抵後送出。',
          '到「更多」選「LINE 通知租客」，或選「列印帳單」產生紙本繳費通知單。',
          '租客上傳繳費截圖後會顯示「待確認」，核對無誤就收款。',
          '在依租客清單按收款，可以修改實收金額；溢繳的部分會轉為預收，下期自動沖抵。',
        ],
        tips: [
          '「分析」分頁看本月收支與電費盈虧，「年度」分頁看各建物損益與綜所稅試算。',
          '房屋稅、地價稅與火險在「更多 › 稅費與保險」登錄。',
        ],
        illustration: 'landlord-billing',
        routeName: 'Financials',
      },
      {
        id: 'landlord-tenants',
        title: '租客帳號、續約與退租',
        icon: 'group',
        location: '側邊欄 › 租客列表 › 點選租客',
        summary: '點租客開啟右側面板，帳號、續約、點交與退租都在這裡處理。',
        steps: [
          '尚無帳號時按「建立租客登入帳號」（帳號為手機號碼、密碼為證件號碼）。',
          '按「產生啟用連結」傳給租客，租客點開連結、輸入證件號碼即可完成首次登入。',
          '租約快到期時按「一鍵續約」設定下一期，目前租期會照舊走完，到期後自動接續；不續約則按「標記不續約」。',
          '退租時先做「退租點交」，再按「辦理退租」結算押金與費用。',
        ],
        tips: [
          '上方統計卡可以快速查看即將到期與逾期欠費的租客。',
          '租客忘記密碼時，按「重設密碼為證件號碼」。',
        ],
        illustration: 'landlord-tenants',
        routeName: 'TenantList',
      },
      {
        id: 'landlord-comms',
        title: '報修、公告與訊息',
        icon: 'campaign',
        location: '側邊欄 › 報修管理／訊息中心；工具 › 社區公告',
        summary: '租客的報修與訊息集中在這裡處理，發布公告也會推播給已綁定 LINE 的租客。',
        steps: [
          '在「報修管理」查看租客的報修內容與照片，更新處理狀態並回覆。',
          '在「社區公告」發布公告，可以設為置頂。',
          '在「訊息中心」回覆租客透過 LINE 或網頁傳來的訊息。',
        ],
        tips: ['側邊欄的紅色數字是尚未處理的項目數量。'],
        illustration: 'landlord-comms',
        routeName: 'RepairRequests',
      },
    ],
  },
  {
    role: 'tenant',
    label: '租客',
    icon: 'person',
    intro: '房東幫您建立帳號後，就可以線上查帳單、上傳繳費截圖、確認合約與報修，綁定 LINE 還能即時收到通知。',
    flow: [
      { label: '啟用帳號', sectionId: 'tenant-login' },
      { label: '確認合約', sectionId: 'tenant-contract' },
      { label: '綁定 LINE', sectionId: 'tenant-line' },
      { label: '每月繳費', sectionId: 'tenant-bills' },
      { label: '報修', sectionId: 'tenant-repair' },
    ],
    sections: [
      {
        id: 'tenant-login',
        title: '啟用帳號與登入',
        icon: 'key',
        location: '房東傳給您的啟用連結／登入頁',
        summary: '第一次請使用房東傳給您的啟用連結，之後用手機號碼和證件號碼登入。',
        steps: [
          '點開房東傳來的啟用連結，輸入證件號碼確認身分。',
          '依畫面引導完成設定（啟用連結只能使用一次）。',
          '之後在登入頁選「身分證登入」，輸入手機號碼與身分證號碼。',
          '看到「綁定 Gmail」提示時可以按「立即綁定」，之後就能直接用 Google 登入。',
        ],
        tips: ['連結過期或打不開，請房東重新產生啟用連結。'],
        illustration: 'tenant-login',
      },
      {
        id: 'tenant-home',
        title: '首頁總覽',
        icon: 'dashboard',
        location: '底部選單（手機）／側邊欄 › 首頁',
        summary: '租約資訊、本月帳單、續租詢問與最新公告，都在首頁一眼看到。',
        steps: [
          '「您的租屋處」顯示租賃期間、每月租金與繳費日。',
          '「本月帳單」顯示應繳金額與電費明細，按「前往繳費」即可繳費。',
          '租約快到期時會出現續租詢問，按「我要續租」或「不續租」回覆房東。',
          '需要協助時按「我要報修」或「聯繫房東」。',
        ],
        illustration: 'tenant-home',
        routeName: 'TenantDashboard',
      },
      {
        id: 'tenant-bills',
        title: '查看帳單與繳費',
        icon: 'receipt_long',
        location: '底部選單 › 帳單',
        summary: '依匯款資訊轉帳後上傳截圖，房東確認收款後帳單就會變成已繳。',
        steps: [
          '點選要繳的帳單，查看明細與房東的匯款帳戶。',
          '轉帳完成後按「前往繳費」。',
          '選擇轉帳截圖後按「送出截圖」。',
          '帳單會顯示「待確認」，房東確認收款後改為已繳。',
        ],
        tips: ['「用電記錄」分頁可以看到每期的電表度數與電費。'],
        illustration: 'tenant-bills',
        routeName: 'TenantBills',
      },
      {
        id: 'tenant-contract',
        title: '確認租賃合約',
        icon: 'history_edu',
        location: '底部選單 › 合約',
        summary: '線上查閱房東建立的合約，確認後會留下電子紀錄。',
        steps: [
          '在需要確認的合約（黃框）按「查閱合約」，詳閱內容。',
          '勾選「我已詳閱此租賃合約…」。',
          '按「確認已收到此合約」，完成後會顯示確認日期。',
        ],
        tips: [
          '合約標籤：待生效（尚未到起租日）、生效中、已被取代（已重新簽約）、已到期。',
          '顯示「僅供查閱」表示房東還沒連結您的帳號，請透過「聯繫房東」告知房東。',
        ],
        illustration: 'tenant-contract',
        routeName: 'TenantMyContract',
      },
      {
        id: 'tenant-line',
        title: '聯繫房東與綁定 LINE',
        icon: 'support_agent',
        location: '底部選單 › 聯繫',
        summary: '綁定 LINE 後，帳單、公告與房東的回覆都會直接傳到您的 LINE。',
        steps: [
          '在「LINE Bot 綁定」掃描 QR Code，或按「加入 LINE Bot」加為好友。',
          '按「取得綁定碼」，畫面會顯示一組數字與倒數時間。',
          '在時間內到 LINE 把這組數字傳給 Bot，完成後顯示「已成功綁定」。',
        ],
        illustration: 'tenant-line',
        routeName: 'ContactLandlord',
      },
      {
        id: 'tenant-repair',
        title: '報修申請',
        icon: 'build_circle',
        location: '底部選單 › 報修',
        summary: '房屋設備有問題時線上報修，可以隨時查看處理進度與房東回覆。',
        steps: [
          '按「立即新增報修」。',
          '選擇設備類別，填寫問題標題、詳細說明與緊急程度。',
          '送出後在列表查看處理狀態與房東回覆。',
        ],
        illustration: 'tenant-repair',
        routeName: 'TenantRepairs',
      },
      {
        id: 'tenant-profile',
        title: '入住點交紀錄與我的資料',
        icon: 'account_circle',
        location: '底部選單 › 點交；手機右上角人像（我的資料）',
        summary: '查閱入住時雙方簽名的點交紀錄，並自行更新聯絡資料與密碼。',
        steps: [
          '在「點交」查看每項物品的狀況、照片與雙方簽名，可以列印成 PDF。',
          '點右上角人像（電腦版在側邊欄底部）進入「我的資料」。',
          '更新電話、聯絡 Email、緊急聯絡人，或變更登入密碼。',
        ],
        illustration: 'tenant-profile',
        routeName: 'TenantProfile',
      },
    ],
  },
  {
    role: 'visitor',
    label: '找房訪客',
    icon: 'travel_explore',
    intro: '不用登入就能瀏覽公開刊登的空房；和房東談好後，透過代碼或填表連結成為租客。',
    flow: [
      { label: '瀏覽空房', sectionId: 'visitor-explore' },
      { label: '查看房東', sectionId: 'visitor-landlord' },
      { label: '成為租客', sectionId: 'visitor-join' },
    ],
    sections: [
      {
        id: 'visitor-explore',
        title: '瀏覽找房頁',
        icon: 'search',
        location: '找房頁（/explore）',
        summary: '所有房東公開刊登的空房都在這裡，可以依格局與價格篩選。',
        steps: [
          '用上方下拉選單篩選格局（套房、雅房、整層住家）與價格。',
          '點房間照片右下角的照片數，放大瀏覽所有照片。',
          '在房間卡片查看租金、坪數，並取得房東聯絡電話。',
        ],
        illustration: 'visitor-explore',
        routeName: 'RoomExplore',
      },
      {
        id: 'visitor-landlord',
        title: '房東頁面與評價',
        icon: 'storefront',
        location: '找房頁 › 點房東名稱',
        summary: '查看房東資料與租客評價作為租屋參考，也可以直接透過 LINE 詢問。',
        steps: [
          '在房間卡片點房東名稱，進入房東資料頁。',
          '按「透過 LINE 詢問」，直接和房東聯繫。',
          '在「租客評價」查看評分、評論與房東的回覆；住過的租客也可以留下評價。',
        ],
        illustration: 'visitor-landlord',
      },
      {
        id: 'visitor-join',
        title: '成為租客',
        icon: 'how_to_reg',
        location: '房東提供的填表連結／註冊頁',
        summary: '和房東談好之後，有兩種方式建立租客資料。',
        steps: [
          '若房東傳來「租客資料填寫」連結：填寫姓名、電話等資料後送出，等房東確認建檔。',
          '若房東提供的是房東代碼：在找房頁按「輸入房東代碼，完成租客註冊」。',
          '房東建檔後會提供啟用連結，之後請參考「租客」分頁操作。',
        ],
        illustration: 'visitor-join',
      },
    ],
  },
  {
    role: 'admin',
    label: '管理員',
    icon: 'admin_panel_settings',
    intro: '系統管理員負責帳號管理、協助房東排除問題與功能維護。模擬房東與資料庫操作會動到正式資料，請謹慎使用。',
    flow: [
      { label: '管理員登入', sectionId: 'admin-overview' },
      { label: '模擬房東', sectionId: 'admin-impersonate' },
      { label: '租客配對', sectionId: 'admin-pairing' },
      { label: '功能開關', sectionId: 'admin-flags' },
    ],
    sections: [
      {
        id: 'admin-overview',
        title: '登入與系統總覽',
        icon: 'dashboard',
        location: '管理員登入頁（/admin/login）› 系統總覽',
        summary: '管理員使用獨立的登入頁，登入後在系統總覽查看整體使用狀況。',
        steps: [
          '前往管理員登入頁，使用管理員帳號登入。',
          '在「系統總覽」查看房東、租客與系統狀態。',
          '從左側選單進入各項管理功能。',
        ],
        illustration: 'admin-overview',
        routeName: 'AdminDashboard',
      },
      {
        id: 'admin-impersonate',
        title: '模擬房東協助排除問題',
        icon: 'manage_accounts',
        location: '側邊欄 › 房東管理',
        summary: '以房東的身分進入房東後台，看到和房東一樣的畫面，方便協助排除問題。',
        steps: [
          '在「房東管理」找到房東，按「以此房東身份模擬操作」。',
          '畫面上方會出現黃色橫幅「正在模擬房東」，此時的操作都會以該房東的身分寫入。',
          '處理完成後，按橫幅上的「結束模擬」回到管理員後台。',
        ],
        tips: ['模擬期間的修改都是正式資料，請只做房東同意的操作。'],
        illustration: 'admin-impersonate',
        routeName: 'AdminLandlords',
      },
      {
        id: 'admin-pairing',
        title: '租客與房東配對',
        icon: 'link',
        location: '側邊欄 › 租客與配對',
        summary: '查看已註冊的租客帳號，協助把租客綁定到正確的房東。',
        steps: [
          '上方「未歸屬（需處理）」是還沒有房東的租客，先從這些處理。',
          '在該租客的操作欄按配對，於「選擇房東」挑選正確的房東。',
          '按「確認配對」完成；租客忘記密碼時，也可以在操作欄重設密碼。',
        ],
        illustration: 'admin-pairing',
        routeName: 'AdminTenants',
      },
      {
        id: 'admin-flags',
        title: '功能維護開關與資料庫',
        icon: 'toggle_on',
        location: '側邊欄 › 功能開關／資料庫操作',
        summary: '某個功能出問題時可以暫時關閉，避免使用者操作到錯誤的功能。',
        steps: [
          '在「功能開關」依房東、租客分區，關閉需要維修的功能。',
          '關閉後該功能會從選單消失，直接輸入網址也只會看到維修中頁面。',
          '修復後再把開關打開即可恢復。',
          '「資料庫操作」與「系統模擬器」用來產生測試資料與模擬情境，請勿在正式房東資料上使用。',
        ],
        illustration: 'admin-flags',
        routeName: 'AdminFeatureFlags',
      },
    ],
  },
];
