<template><div class="max-w-5xl mx-auto space-y-6"><div class="flex justify-between gap-4"><div><h1 class="text-2xl font-bold">歷史資料遷移</h1><p class="text-text-secondary-light">以舊系統鍵搬入已退租租客、歷史帳單與付款；不觸發催繳或通知。</p></div><button class="px-4 py-2 bg-gold-500 text-white rounded-xl" @click="template">下載歷史範本</button></div><label class="block p-10 text-center border-2 border-dashed rounded-2xl cursor-pointer"><span class="material-symbols-outlined text-4xl text-gold-500">upload_file</span><p>{{ parsing ? '解析中…' : '選擇歷史 Excel' }}</p><input class="hidden" type="file" accept=".xlsx,.xls,.xlsm" @change="read"></label><section v-if="fileName" class="p-5 bg-white dark:bg-card-dark rounded-2xl border space-y-3"><div class="flex justify-between"><span>{{ fileName }}：{{ errors.length ? `發現 ${errors.length} 項錯誤` : `租客 ${plan?.tenants.length || 0}、帳單 ${plan?.bills.length || 0}` }}</span><button v-if="plan" class="px-4 py-2 bg-gold-500 text-white rounded-xl" :disabled="importing" @click="save">{{ importing?'匯入中…':'確認匯入' }}</button></div><ul v-if="errors.length" class="text-red-600 text-sm"><li v-for="e in errors" :key="e">{{e}}</li></ul><p v-if="done" class="text-green-600">完成，任務編號：{{done}}</p></section></div></template>
<script setup lang="ts">
import { ref } from 'vue'; import { useAuthStore } from '../../stores/auth'; import { useToastStore } from '../../stores/toast'; import { buildHistoricalImportPlan } from '../../utils/historicalImport'; import { executeHistoricalImport } from '../../services/landlordImportService'
const auth=useAuthStore(),toast=useToastStore(),parsing=ref(false),importing=ref(false),fileName=ref(''),errors=ref<string[]>([]),plan=ref<NonNullable<ReturnType<typeof buildHistoricalImportPlan>['plan']>>(),done=ref('')
const headers={ tenants:['舊租客鍵','姓名','舊房間鍵','退租日','電話'], bills:['舊帳單鍵','舊租客鍵','帳單日','到期日','類別','金額','說明'], payments:['舊付款鍵','舊帳單鍵','付款日','金額','方式','備註'] } as const
const names={tenants:'歷史租客',bills:'歷史帳單',payments:'歷史付款'} as const
const val=(x:unknown)=>x instanceof Date?x.toISOString().slice(0,10):String(x??'').trim(); const rows=(X:any,w:any,k:keyof typeof headers)=>{const s=w.Sheets[names[k]];return s?(X.utils.sheet_to_json(s,{header:1,defval:'',raw:false}) as unknown[][]).slice(1).filter(r=>r.some(x=>String(x).trim())).map(r=>r.map(val)):[]}
const read=async(e:Event)=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;parsing.value=true;try{const X=await import('xlsx'),w=X.read(await f.arrayBuffer(),{type:'array',cellDates:true}),t=rows(X,w,'tenants'),b=rows(X,w,'bills'),p=rows(X,w,'payments');const r=buildHistoricalImportPlan({tenants:t.map(x=>({legacyTenantKey:x[0] as string,name:x[1] as string,legacyRoomKey:x[2] as string,moveOutDate:x[3] as string,phone:x[4] as string})),bills:b.map(x=>({legacyBillKey:x[0] as string,legacyTenantKey:x[1] as string,date:x[2] as string,dueDate:x[3] as string,category:x[4] as string,amount:x[5],description:x[6] as string})),payments:p.map(x=>({legacyPaymentKey:x[0] as string,legacyBillKey:x[1] as string,date:x[2] as string,amount:x[3],method:x[4] as string,note:x[5] as string}))});fileName.value=f.name;errors.value=r.errors;plan.value=r.plan}catch{toast.error('Excel 解析失敗')}finally{parsing.value=false}}
const save=async()=>{if(!plan.value||!auth.effectiveUid)return;importing.value=true;try{const r=await executeHistoricalImport(auth.effectiveUid,plan.value,fileName.value);done.value=r.runId;toast.success('歷史資料已匯入')}catch(e:any){toast.error(e?.message||'匯入失敗')}finally{importing.value=false}}
const template=async()=>{const X=await import('xlsx'),w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet([['歷史資料遷移範本 v2'],['日期一律 YYYY-MM-DD；所有跨表關聯使用舊系統鍵。']]),'填寫說明');Object.entries(headers).forEach(([k,h])=>X.utils.book_append_sheet(w,X.utils.aoa_to_sheet([[...h]]),names[k as keyof typeof headers]));X.writeFile(w,'歷史資料遷移範本_v2.xlsx')}
</script>
